/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diagramadoruml;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author samuelzun
 */
public class frm_Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_Main.class.getName());

    /**
     * Creates new form GUI
     */
    public frm_Main() {
        
        ClaseUML claseTest = new ClaseUML("Test", null);
        claseTest.getPropiedades().add(new Propiedad("propPrivado", Tipo.STRING, Acceso.PRIVATE));
        claseTest.getPropiedades().add(new Propiedad("propProtegido", Tipo.STRING, Acceso.PROTECTED));
        this.clases.add(claseTest);
        
        initComponents();
        
        DefaultComboBoxModel paramModeloTipo = (DefaultComboBoxModel) this.cbox_CrearParamTipo.getModel();
        paramModeloTipo.removeAllElements();
        for (int i = 1; i < Tipo.values().length; i++) {
            paramModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel propModeloTipo = (DefaultComboBoxModel) this.cbox_CrearPropTipo.getModel();
        propModeloTipo.removeAllElements();
        for (int i = 1; i < Tipo.values().length; i++) {
            propModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel propModeloAcceso = (DefaultComboBoxModel) this.cbox_CrearPropAcceso.getModel();
        propModeloAcceso.removeAllElements();
        for (Acceso acceso: Acceso.values()) {
            propModeloAcceso.addElement(
                    acceso
            );
        }
        
        DefaultComboBoxModel metModeloTipo = (DefaultComboBoxModel) this.cbox_CrearMetTipo.getModel();
        metModeloTipo.removeAllElements();
        for (int i = 0; i < Tipo.values().length; i++) {
            metModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel metModeloAcceso = (DefaultComboBoxModel) this.cbox_CrearMetAcceso.getModel();
        metModeloAcceso.removeAllElements();
        for (Acceso acceso: Acceso.values()) {
            metModeloAcceso.addElement(
                    acceso
            );
        }
        
        this.list_CrearMetParametros.setModel(new DefaultListModel());
        this.list_HerenciaClaseHija.setModel(new DefaultListModel());
        this.list_HerenciaClasePadre.setModel(new DefaultListModel());
        
        
        DefaultListModel hernModeloHijo = (DefaultListModel) this.list_HerenciaClaseHija.getModel();
        hernModeloHijo.removeAllElements();
        for (ClaseUML clase: clases) {
            hernModeloHijo.addElement(
                    clase
            );
        }
        
        DefaultListModel hernModeloPadre = (DefaultListModel) this.list_HerenciaClasePadre.getModel();
        hernModeloPadre.removeAllElements();
        hernModeloPadre.addElement("Sin padre");
        for (ClaseUML clase: clases) {
            hernModeloPadre.addElement(
                    clase
            );
        }
        
        this.cbox_CrearClasePadre.setModel(
                crearCBoxModelParaClasesPadre()
        );
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diag_Clases = new javax.swing.JDialog();
        pnl_Clases = new javax.swing.JPanel();
        lbl_Clases = new javax.swing.JLabel();
        tab_Clases = new javax.swing.JTabbedPane();
        pnl_ClasesDiagrama = new javax.swing.JPanel();
        pnl_ClasesCodigo = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txta_CodigoClases = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_Clases = new javax.swing.JTree();
        btn_ClasesHerencia = new javax.swing.JButton();
        btn_ClasesHerencia1 = new javax.swing.JButton();
        mnb_Clases = new javax.swing.JMenuBar();
        mnb_ClasesArchivo = new javax.swing.JMenu();
        mnb_ClasesAbrir = new javax.swing.JMenuItem();
        mnb_ClasesGuardar = new javax.swing.JMenuItem();
        mnb_ClasesExportar = new javax.swing.JMenu();
        mnb_ClasesExpPDF = new javax.swing.JMenuItem();
        diag_Flujo = new javax.swing.JDialog();
        diag_CrearVariable = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        diag_CrearClase = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_CrearClaseNombre = new javax.swing.JTextField();
        cbox_CrearClasePadre = new javax.swing.JComboBox<>();
        btn_CrearClase = new javax.swing.JToggleButton();
        pop_Clases = new javax.swing.JPopupMenu();
        popmi_ClaseCambiarNombre = new javax.swing.JMenuItem();
        popmi_ClaseAgregarPropiedad = new javax.swing.JMenuItem();
        popmi_ClaseAgregarMetodo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        popmi_ClaseEliminar = new javax.swing.JMenuItem();
        diag_CambiarNombre = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_ClaseCambiarNombre = new javax.swing.JTextField();
        btn_ClaseCambiarNombre = new javax.swing.JToggleButton();
        pop_Propiedades = new javax.swing.JPopupMenu();
        popmi_PropCambiarNombre = new javax.swing.JMenuItem();
        diag_CrearProp = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_CrearPropNombre = new javax.swing.JTextField();
        cbox_CrearPropTipo = new javax.swing.JComboBox<>();
        btn_CrearProp = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        cbox_CrearPropAcceso = new javax.swing.JComboBox<>();
        diag_CrearMetodo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_CrearMetNombre = new javax.swing.JTextField();
        cbox_CrearMetTipo = new javax.swing.JComboBox<>();
        btn_CrearMet = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        cbox_CrearMetAcceso = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_CrearMetParametros = new javax.swing.JList<>();
        btn_CrearMetAgregarParametro = new javax.swing.JToggleButton();
        diag_CrearParametro = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        txt_CrearParamNombre = new javax.swing.JTextField();
        btn_CrearParam = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        cbox_CrearParamTipo = new javax.swing.JComboBox<>();
        diag_Herencia = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_HerenciaClasePadre = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_HerenciaClaseHija = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        btn_EstablecerHerencia = new javax.swing.JButton();
        mnb_Principal = new javax.swing.JMenuBar();
        mn_PrincipalFunciones = new javax.swing.JMenu();
        mni_PrincipalFlujo = new javax.swing.JMenuItem();
        mni_PrincipalClases = new javax.swing.JMenuItem();

        diag_Clases.setPreferredSize(new java.awt.Dimension(1280, 720));
        diag_Clases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diag_ClasesFocusGained(evt);
            }
        });
        diag_Clases.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                diag_ClasesComponentShown(evt);
            }
        });

        lbl_Clases.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_Clases.setText("Clases");

        tab_Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ClasesMouseClicked(evt);
            }
        });

        pnl_ClasesDiagrama.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnl_ClasesDiagramaLayout = new javax.swing.GroupLayout(pnl_ClasesDiagrama);
        pnl_ClasesDiagrama.setLayout(pnl_ClasesDiagramaLayout);
        pnl_ClasesDiagramaLayout.setHorizontalGroup(
            pnl_ClasesDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        pnl_ClasesDiagramaLayout.setVerticalGroup(
            pnl_ClasesDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        tab_Clases.addTab("Diagrama", pnl_ClasesDiagrama);

        txta_CodigoClases.setColumns(20);
        txta_CodigoClases.setRows(5);
        jScrollPane5.setViewportView(txta_CodigoClases);

        javax.swing.GroupLayout pnl_ClasesCodigoLayout = new javax.swing.GroupLayout(pnl_ClasesCodigo);
        pnl_ClasesCodigo.setLayout(pnl_ClasesCodigoLayout);
        pnl_ClasesCodigoLayout.setHorizontalGroup(
            pnl_ClasesCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_ClasesCodigoLayout.setVerticalGroup(
            pnl_ClasesCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_Clases.addTab("Código", pnl_ClasesCodigo);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_Clases.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_ClasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tree_Clases);

        btn_ClasesHerencia.setText("Herencia");
        btn_ClasesHerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClasesHerenciaActionPerformed(evt);
            }
        });

        btn_ClasesHerencia1.setText("Nueva Clase");
        btn_ClasesHerencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClasesHerencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ClasesLayout = new javax.swing.GroupLayout(pnl_Clases);
        pnl_Clases.setLayout(pnl_ClasesLayout);
        pnl_ClasesLayout.setHorizontalGroup(
            pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesLayout.createSequentialGroup()
                .addGroup(pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_Clases))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btn_ClasesHerencia))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_ClasesHerencia1)))
                .addGap(97, 97, 97)
                .addComponent(tab_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnl_ClasesLayout.setVerticalGroup(
            pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addComponent(lbl_Clases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btn_ClasesHerencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ClasesHerencia1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mnb_ClasesArchivo.setText("Archivo");

        mnb_ClasesAbrir.setText("Abrir");
        mnb_ClasesArchivo.add(mnb_ClasesAbrir);

        mnb_ClasesGuardar.setText("Guardar");
        mnb_ClasesArchivo.add(mnb_ClasesGuardar);

        mnb_Clases.add(mnb_ClasesArchivo);

        mnb_ClasesExportar.setText("Exportar");

        mnb_ClasesExpPDF.setText("Exportar como PDF");
        mnb_ClasesExportar.add(mnb_ClasesExpPDF);

        mnb_Clases.add(mnb_ClasesExportar);

        diag_Clases.setJMenuBar(mnb_Clases);

        javax.swing.GroupLayout diag_ClasesLayout = new javax.swing.GroupLayout(diag_Clases.getContentPane());
        diag_Clases.getContentPane().setLayout(diag_ClasesLayout);
        diag_ClasesLayout.setHorizontalGroup(
            diag_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClasesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        diag_ClasesLayout.setVerticalGroup(
            diag_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClasesLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(pnl_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diag_FlujoLayout = new javax.swing.GroupLayout(diag_Flujo.getContentPane());
        diag_Flujo.getContentPane().setLayout(diag_FlujoLayout);
        diag_FlujoLayout.setHorizontalGroup(
            diag_FlujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        diag_FlujoLayout.setVerticalGroup(
            diag_FlujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Alcance:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Variable:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "long", "float", "double", "char", "String" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "public", "private", "protected" }));

        jToggleButton1.setText("Crear variable");

        javax.swing.GroupLayout diag_CrearVariableLayout = new javax.swing.GroupLayout(diag_CrearVariable.getContentPane());
        diag_CrearVariable.getContentPane().setLayout(diag_CrearVariableLayout);
        diag_CrearVariableLayout.setHorizontalGroup(
            diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearVariableLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 145, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearVariableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(105, 105, 105))
        );
        diag_CrearVariableLayout.setVerticalGroup(
            diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearVariableLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jToggleButton1)
                .addGap(29, 29, 29))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Padre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nombre:");

        cbox_CrearClasePadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearClase.setText("Crear clase");
        btn_CrearClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CrearClaseLayout = new javax.swing.GroupLayout(diag_CrearClase.getContentPane());
        diag_CrearClase.getContentPane().setLayout(diag_CrearClaseLayout);
        diag_CrearClaseLayout.setHorizontalGroup(
            diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearClaseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_CrearClaseNombre)
                    .addComponent(cbox_CrearClasePadre, 0, 145, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearClaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CrearClase)
                .addGap(105, 105, 105))
        );
        diag_CrearClaseLayout.setVerticalGroup(
            diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearClaseLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_CrearClaseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbox_CrearClasePadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btn_CrearClase)
                .addGap(29, 29, 29))
        );

        popmi_ClaseCambiarNombre.setText("Cambiar nombre");
        popmi_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseCambiarNombreActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseCambiarNombre);

        popmi_ClaseAgregarPropiedad.setText("Agregar propiedad");
        popmi_ClaseAgregarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseAgregarPropiedadActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseAgregarPropiedad);

        popmi_ClaseAgregarMetodo.setText("Crear método");
        popmi_ClaseAgregarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseAgregarMetodoActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseAgregarMetodo);
        pop_Clases.add(jSeparator1);

        popmi_ClaseEliminar.setText("Eliminar esta clase");
        popmi_ClaseEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseEliminarActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseEliminar);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        btn_ClaseCambiarNombre.setText("Cambiar nombre");
        btn_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClaseCambiarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CambiarNombreLayout = new javax.swing.GroupLayout(diag_CambiarNombre.getContentPane());
        diag_CambiarNombre.getContentPane().setLayout(diag_CambiarNombreLayout);
        diag_CambiarNombreLayout.setHorizontalGroup(
            diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                .addGroup(diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_ClaseCambiarNombre)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CambiarNombreLayout.setVerticalGroup(
            diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn_ClaseCambiarNombre)
                .addGap(40, 40, 40))
        );

        popmi_PropCambiarNombre.setText("Cambiar nombre");
        popmi_PropCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_PropCambiarNombreActionPerformed(evt);
            }
        });
        pop_Propiedades.add(popmi_PropCambiarNombre);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tipo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        cbox_CrearPropTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearProp.setText("Crear propiedad");
        btn_CrearProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearPropActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Acceso:");

        cbox_CrearPropAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        javax.swing.GroupLayout diag_CrearPropLayout = new javax.swing.GroupLayout(diag_CrearProp.getContentPane());
        diag_CrearProp.getContentPane().setLayout(diag_CrearPropLayout);
        diag_CrearPropLayout.setHorizontalGroup(
            diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearPropLayout.createSequentialGroup()
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearPropLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35)
                        .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbox_CrearPropAcceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_CrearPropNombre)
                            .addComponent(cbox_CrearPropTipo, 0, 145, Short.MAX_VALUE)))
                    .addGroup(diag_CrearPropLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_CrearProp)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CrearPropLayout.setVerticalGroup(
            diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearPropLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_CrearPropNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbox_CrearPropTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbox_CrearPropAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btn_CrearProp)
                .addGap(31, 31, 31))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Retorno:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nombre:");

        cbox_CrearMetTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearMet.setText("Crear método");
        btn_CrearMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearMetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Acceso:");

        cbox_CrearMetAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        list_CrearMetParametros.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(list_CrearMetParametros);

        btn_CrearMetAgregarParametro.setText("Agregar\nparámetro");
        btn_CrearMetAgregarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearMetAgregarParametroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CrearMetodoLayout = new javax.swing.GroupLayout(diag_CrearMetodo.getContentPane());
        diag_CrearMetodo.getContentPane().setLayout(diag_CrearMetodoLayout);
        diag_CrearMetodoLayout.setHorizontalGroup(
            diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(btn_CrearMetAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbox_CrearMetAcceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_CrearMetNombre)
                                .addComponent(cbox_CrearMetTipo, 0, 145, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_CrearMet)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        diag_CrearMetodoLayout.setVerticalGroup(
            diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_CrearMetNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbox_CrearMetTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbox_CrearMetAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearMetodoLayout.createSequentialGroup()
                        .addComponent(btn_CrearMetAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(btn_CrearMet)
                .addGap(39, 39, 39))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nombre:");

        btn_CrearParam.setText("Crear parametro");
        btn_CrearParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearParamActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Tipo:");

        cbox_CrearParamTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout diag_CrearParametroLayout = new javax.swing.GroupLayout(diag_CrearParametro.getContentPane());
        diag_CrearParametro.getContentPane().setLayout(diag_CrearParametroLayout);
        diag_CrearParametroLayout.setHorizontalGroup(
            diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_CrearParam))
                    .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CrearParamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_CrearParamTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CrearParametroLayout.setVerticalGroup(
            diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txt_CrearParamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbox_CrearParamTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_CrearParam)
                .addGap(40, 40, 40))
        );

        list_HerenciaClasePadre.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(list_HerenciaClasePadre);

        list_HerenciaClaseHija.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(list_HerenciaClaseHija);

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel15.setText("Sera padre de:");

        btn_EstablecerHerencia.setText("Establecer herencia");
        btn_EstablecerHerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstablecerHerenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_HerenciaLayout = new javax.swing.GroupLayout(diag_Herencia.getContentPane());
        diag_Herencia.getContentPane().setLayout(diag_HerenciaLayout);
        diag_HerenciaLayout.setHorizontalGroup(
            diag_HerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_HerenciaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_HerenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_EstablecerHerencia)
                .addGap(170, 170, 170))
        );
        diag_HerenciaLayout.setVerticalGroup(
            diag_HerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_HerenciaLayout.createSequentialGroup()
                .addGroup(diag_HerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_HerenciaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(diag_HerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_HerenciaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btn_EstablecerHerencia)
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mn_PrincipalFunciones.setText("Funciones");

        mni_PrincipalFlujo.setText("Diagramas de Flujo");
        mni_PrincipalFlujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mni_PrincipalFlujoMouseClicked(evt);
            }
        });
        mni_PrincipalFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PrincipalFlujoActionPerformed(evt);
            }
        });
        mn_PrincipalFunciones.add(mni_PrincipalFlujo);

        mni_PrincipalClases.setText("Diagramas de Clases");
        mni_PrincipalClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PrincipalClasesActionPerformed(evt);
            }
        });
        mn_PrincipalFunciones.add(mni_PrincipalClases);

        mnb_Principal.add(mn_PrincipalFunciones);

        setJMenuBar(mnb_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_PrincipalFlujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mni_PrincipalFlujoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_PrincipalFlujoMouseClicked

    private void mni_PrincipalFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PrincipalFlujoActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_Flujo);
        
    }//GEN-LAST:event_mni_PrincipalFlujoActionPerformed

    private void mni_PrincipalClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PrincipalClasesActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_Clases);
       
    }//GEN-LAST:event_mni_PrincipalClasesActionPerformed

    private void btn_CrearClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearClaseActionPerformed
        // TODO add your handling code here:
        try  {
            if (!this.txt_CrearClaseNombre.getText().trim().isEmpty())  {
                switch (this.cbox_CrearClasePadre.getSelectedIndex()) {
                    case 0 -> {
                        crearClaseUML(
                            this.txt_CrearClaseNombre.getText()
                        );
                    }
                    default -> {
                        ClaseUML clasePadre =  (ClaseUML) this.cbox_CrearClasePadre.getSelectedItem();
                        clasePadre.getHijos().add(new ClaseUML(
                            this.txt_CrearClaseNombre.getText(),
                            clasePadre
                        ));
                    }
                }
                this.cbox_CrearClasePadre.setModel(
                        crearCBoxModelParaClasesPadre()
                );
                refrescarModelosClase();
                this.diag_CrearClase.dispose();
                limpiar(this.txt_CrearClaseNombre);
                enviarMensaje(this.diag_Clases, "Clase creada.");
            }
        } catch (Exception e)  {
            imprimirError(e, evt);
        }
    }//GEN-LAST:event_btn_CrearClaseActionPerformed

    private void diag_ClasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diag_ClasesFocusGained
        // TODO add your handling code here:
        refrescarModelosClase();
        
    }//GEN-LAST:event_diag_ClasesFocusGained

    private void btn_ClasesHerencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClasesHerencia1ActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_CrearClase);
        
    }//GEN-LAST:event_btn_ClasesHerencia1ActionPerformed

    private void diag_ClasesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_diag_ClasesComponentShown
        // TODO add your handling code here:
        refrescarModelosClase();
        
    }//GEN-LAST:event_diag_ClasesComponentShown

    private void popmi_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:
        
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {
            
            this.txt_ClaseCambiarNombre.setText(clase.getNombre());
            
        }
        mostrarJDialog(this.diag_CambiarNombre);
        
    }//GEN-LAST:event_popmi_ClaseCambiarNombreActionPerformed

    private void tree_ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_ClasesMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            
            Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
            if (objetoSeleccionado instanceof ClaseUML) {
                this.pop_Clases.show(this.tree_Clases, evt.getX(), evt.getY());
            } else if (objetoSeleccionado instanceof Propiedad) {
                this.pop_Propiedades.show(this.tree_Clases, evt.getX(), evt.getY());
            }
            
        }
        
    }//GEN-LAST:event_tree_ClasesMouseClicked

    private void btn_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof ClaseUML clase) {
            
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                clase.setNombre(this.txt_ClaseCambiarNombre.getText());
                this.diag_CambiarNombre.dispose();
                enviarMensaje(this.diag_Clases, "Nombre cambiado.");
            }
            
        } else if (objetoSeleccionado instanceof Propiedad prop) {
            
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                prop.setNombre(this.txt_ClaseCambiarNombre.getText());
                this.diag_CambiarNombre.dispose();
                enviarMensaje(this.diag_Clases, "Nombre cambiado.");
            }
            
        }
    }//GEN-LAST:event_btn_ClaseCambiarNombreActionPerformed

    private void popmi_PropCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_PropCambiarNombreActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof Propiedad prop) {
            
            this.txt_ClaseCambiarNombre.setText(prop.getNombre());
            
        }
        mostrarJDialog(this.diag_CambiarNombre);
        
    }//GEN-LAST:event_popmi_PropCambiarNombreActionPerformed

    private void popmi_ClaseAgregarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseAgregarPropiedadActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_CrearProp);
        
    }//GEN-LAST:event_popmi_ClaseAgregarPropiedadActionPerformed

    private void btn_CrearPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearPropActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {
            
            try {
                if (!this.txt_CrearPropNombre.getText().trim().isEmpty()) {

                    clase.getPropiedades().add(
                            new Propiedad(
                                    this.txt_CrearPropNombre.getText(),
                                    (Tipo) this.cbox_CrearPropTipo.getSelectedItem(),
                                    (Acceso) this.cbox_CrearPropAcceso.getSelectedItem()
                            )
                    );
                    this.diag_CrearProp.dispose();
                    refrescarModelosClase();
                    enviarMensaje(this.diag_Clases, "Clase creada.");

                }
            } catch (Exception e) {
                imprimirError(e, evt);
            }
            
        }
        
    }//GEN-LAST:event_btn_CrearPropActionPerformed

    private void popmi_ClaseEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseEliminarActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof ClaseUML clase) {
            
            clases.remove(clase);
            refrescarModelosClase();
            enviarMensaje(this.diag_Clases, "Clase removida");
            
        }
        
    }//GEN-LAST:event_popmi_ClaseEliminarActionPerformed

    private void btn_CrearMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearMetActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {
            
            try {
                if (!this.txt_CrearMetNombre.getText().trim().isEmpty()) {
                    
                    Metodo nuevoMetodo = new Metodo(
                            this.txt_CrearMetNombre.getText(),
                            (Tipo) this.cbox_CrearMetTipo.getSelectedItem(),
                            (Acceso) this.cbox_CrearMetAcceso.getSelectedItem()
                    );
                    
                    if (this.list_CrearMetParametros.getModel().getSize() != 0) {
                        for (int i = 0; i < this.list_CrearMetParametros.getModel().getSize(); i++) {
                            nuevoMetodo.getParametros().add(
                                    (Propiedad) ( (DefaultListModel) this.list_CrearMetParametros.getModel() ).get(i)
                            );
                        }
                        ( (DefaultListModel) this.list_CrearMetParametros.getModel() ).removeAllElements();
                    }
                    
                    clase.getMetodos().add(
                            nuevoMetodo
                    );
                    
                    refrescarModelosClase();
                    this.diag_CrearMetodo.dispose();
                    limpiar(this.txt_CrearMetNombre);
                    enviarMensaje(this.diag_Clases, "Método creado.");

                }
            } catch (Exception e) {
                imprimirError(e, evt);
            }
            
        } else {
            System.out.println("hola");
        }
        
    }//GEN-LAST:event_btn_CrearMetActionPerformed

    private void btn_CrearParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearParamActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = (DefaultListModel) this.list_CrearMetParametros.getModel();
        Propiedad param = new Propiedad(
                this.txt_CrearParamNombre.getText(),
                (Tipo) this.cbox_CrearParamTipo.getSelectedItem()
        );
        modeloLista.addElement(param);
        this.diag_CrearParametro.dispose();
        
    }//GEN-LAST:event_btn_CrearParamActionPerformed

    private void btn_CrearMetAgregarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearMetAgregarParametroActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_CrearParametro);
        
    }//GEN-LAST:event_btn_CrearMetAgregarParametroActionPerformed

    private void popmi_ClaseAgregarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseAgregarMetodoActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_CrearMetodo);
        
    }//GEN-LAST:event_popmi_ClaseAgregarMetodoActionPerformed

    private void btn_EstablecerHerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstablecerHerenciaActionPerformed
        // TODO add your handling code here:
        if (this.list_HerenciaClaseHija.getSelectedIndex() != this.list_HerenciaClasePadre.getSelectedIndex()-1) {
            
            ClaseUML claseHija = (ClaseUML) ( (DefaultListModel) this.list_HerenciaClaseHija.getModel() ).get(
                    this.list_HerenciaClaseHija.getSelectedIndex()
            );
            ClaseUML clasePadre;
            
            switch (this.list_HerenciaClasePadre.getSelectedIndex()) {
                case 0 -> {
                    clasePadre = null;
                }
                default -> {
                    clasePadre = (ClaseUML) ( (DefaultListModel) this.list_HerenciaClasePadre.getModel() ).get(
                            this.list_HerenciaClasePadre.getSelectedIndex()
                    );
                }
            }
            
            if (clasePadre == null) {
                claseHija.getClasePadre().getHijos().remove(claseHija);
                claseHija.setClasePadre(clasePadre);
            } else {
                claseHija.getClasePadre().getHijos().remove(claseHija);
                claseHija.setClasePadre(clasePadre);
                claseHija.getClasePadre().getHijos().add(claseHija);
            }
            
            this.diag_Herencia.dispose();
            refrescarModelosClase();
            enviarMensaje(this.diag_Clases, "Herencia establecida.");
            
        } else {
            
        }
        
    }//GEN-LAST:event_btn_EstablecerHerenciaActionPerformed

    private void btn_ClasesHerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClasesHerenciaActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_Herencia);
        
    }//GEN-LAST:event_btn_ClasesHerenciaActionPerformed

    private void tab_ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ClasesMouseClicked
        // TODO add your handling code here:
//        if (this.tab_Clases.getSelectedIndex() == 1 && !this.clases.isEmpty()) {
//            
//            this.txta_CodigoClases.setText(clasesACodigo())
//            
//        }
                
    }//GEN-LAST:event_tab_ClasesMouseClicked
    
    private String clasesACodigo() {
        System.out.println(clasesACodigo("", this.clases));
        return clasesACodigo("", this.clases);
    }
    
    private String clasesACodigo(String str, ArrayList<ClaseUML> clases) {
        for (ClaseUML clase: clases) {
            str += clase.claseEnCodigo()+"\n\n";
            if (!clase.getHijos().isEmpty()) {
                str = clasesACodigo(str, clase.getHijos());
            }
        }
        return str;
    }
    
    private DefaultTreeModel crearTreeModelClases() {
        return crearTreeModelClases(
                new DefaultMutableTreeNode("Clases"),
                this.clases
        );
    }
    
    private DefaultTreeModel crearTreeModelClases(DefaultMutableTreeNode nodoRaiz, ArrayList<ClaseUML> clases) {
        
        for (ClaseUML clase: clases) {
            nodoRaiz.add(clase.formaNodo());
            if (!clase.getHijos().isEmpty()) {
                crearTreeModelClases(
                        nodoRaiz
                        ,clase.getHijos()
                );
            }
        }
        
        return new DefaultTreeModel(nodoRaiz);
        
    }
    
    private DefaultListModel crearListModelClases() {
        return crearListModelClases(new DefaultListModel(), this.clases);
    }
    
    private DefaultListModel crearListModelClases(DefaultListModel modelo, ArrayList<ClaseUML> clases) {
        
        for (ClaseUML clase: clases) {
            
            modelo.addElement(clase);
            if (!clase.getHijos().isEmpty()) {
                crearListModelClases(
                        modelo,
                        clase.getHijos()
                );
            }
                    
        }
        return modelo;
        
    }
    
    private DefaultListModel crearListModelClases(DefaultListModel modelo) {
        
        DefaultListModel elementos = crearListModelClases();
        for (int i = 0; i < elementos.getSize(); i++) {
            modelo.addElement(
                    (ClaseUML) elementos.get(i)
            );
        }
        return modelo;
        
    }
    
    private void refrescarModelosClase() {
        
        this.tree_Clases.setModel(crearTreeModelClases());
        this.list_HerenciaClaseHija.setModel(
                crearListModelClases()
        );
        DefaultListModel modeloPadre = new DefaultListModel();
        modeloPadre.addElement("Sin padre");
        this.list_HerenciaClasePadre.setModel(
                crearListModelClases(modeloPadre)
        );
        DefaultComboBoxModel modeloPadreCBox = new DefaultComboBoxModel();
        modeloPadreCBox.addElement("Sin padre");
        this.cbox_CrearClasePadre.setModel(
                crearCBoxModelParaClasesPadre(modeloPadreCBox)
        );
        this.txta_CodigoClases.setText(clasesACodigo());
        
    }
    
    private DefaultComboBoxModel crearCBoxModelParaClasesPadre() {
        return crearCBoxModelParaClasesPadre(new DefaultComboBoxModel(), this.clases);
    }
    
    private DefaultComboBoxModel crearCBoxModelParaClasesPadre(DefaultComboBoxModel modelo) {
        
        DefaultComboBoxModel elementos = crearCBoxModelParaClasesPadre();
        for (int i = 0; i < elementos.getSize(); i++) {
            modelo.addElement(
                    (ClaseUML) elementos.getElementAt(i)
            );
        }
        return modelo;
        
    }
    
    private DefaultComboBoxModel crearCBoxModelParaClasesPadre(DefaultComboBoxModel modelo, ArrayList<ClaseUML> clases) {
        
        for (ClaseUML clase: clases) {
            
            modelo.addElement(clase);
            if (!clase.getHijos().isEmpty()) {
                crearCBoxModelParaClasesPadre(
                        modelo,
                        clase.getHijos()
                );
            }
                    
        }
        return modelo;
    }
    
    private void mostrarJDialog(javax.swing.JDialog diag) {
        diag.pack();
        diag.setVisible(true);
    }
    
    private void limpiar(javax.swing.JTextField txt) {
        txt.setText("");
    }
    
    private void enviarMensaje(Component comp, String msg) {
        JOptionPane.showMessageDialog(comp, msg, "", -1);
    }
    
    private void crearClaseUML(String nombre) {
        clases.add(new ClaseUML(
                nombre
        ));
    }
    private void crearClaseUML(String nombre, ClaseUML padre) {
        clases.add(new ClaseUML(
                nombre,
                padre
        ));
    }
    
    private void imprimirError(Exception e, java.awt.event.ActionEvent evt) {
        System.out.println(e.getCause()+" en "+evt.getActionCommand());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Main().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ClaseCambiarNombre;
    private javax.swing.JButton btn_ClasesHerencia;
    private javax.swing.JButton btn_ClasesHerencia1;
    private javax.swing.JToggleButton btn_CrearClase;
    private javax.swing.JToggleButton btn_CrearMet;
    private javax.swing.JToggleButton btn_CrearMetAgregarParametro;
    private javax.swing.JToggleButton btn_CrearParam;
    private javax.swing.JToggleButton btn_CrearProp;
    private javax.swing.JButton btn_EstablecerHerencia;
    private javax.swing.JComboBox<String> cbox_CrearClasePadre;
    private javax.swing.JComboBox<String> cbox_CrearMetAcceso;
    private javax.swing.JComboBox<String> cbox_CrearMetTipo;
    private javax.swing.JComboBox<String> cbox_CrearParamTipo;
    private javax.swing.JComboBox<String> cbox_CrearPropAcceso;
    private javax.swing.JComboBox<String> cbox_CrearPropTipo;
    private javax.swing.JDialog diag_CambiarNombre;
    private javax.swing.JDialog diag_Clases;
    private javax.swing.JDialog diag_CrearClase;
    private javax.swing.JDialog diag_CrearMetodo;
    private javax.swing.JDialog diag_CrearParametro;
    private javax.swing.JDialog diag_CrearProp;
    private javax.swing.JDialog diag_CrearVariable;
    private javax.swing.JDialog diag_Flujo;
    private javax.swing.JDialog diag_Herencia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_Clases;
    private javax.swing.JList<String> list_CrearMetParametros;
    private javax.swing.JList<String> list_HerenciaClaseHija;
    private javax.swing.JList<String> list_HerenciaClasePadre;
    private javax.swing.JMenu mn_PrincipalFunciones;
    private javax.swing.JMenuBar mnb_Clases;
    private javax.swing.JMenuItem mnb_ClasesAbrir;
    private javax.swing.JMenu mnb_ClasesArchivo;
    private javax.swing.JMenuItem mnb_ClasesExpPDF;
    private javax.swing.JMenu mnb_ClasesExportar;
    private javax.swing.JMenuItem mnb_ClasesGuardar;
    private javax.swing.JMenuBar mnb_Principal;
    private javax.swing.JMenuItem mni_PrincipalClases;
    private javax.swing.JMenuItem mni_PrincipalFlujo;
    private javax.swing.JPanel pnl_Clases;
    private javax.swing.JPanel pnl_ClasesCodigo;
    private javax.swing.JPanel pnl_ClasesDiagrama;
    private javax.swing.JPopupMenu pop_Clases;
    private javax.swing.JPopupMenu pop_Propiedades;
    private javax.swing.JMenuItem popmi_ClaseAgregarMetodo;
    private javax.swing.JMenuItem popmi_ClaseAgregarPropiedad;
    private javax.swing.JMenuItem popmi_ClaseCambiarNombre;
    private javax.swing.JMenuItem popmi_ClaseEliminar;
    private javax.swing.JMenuItem popmi_PropCambiarNombre;
    private javax.swing.JTabbedPane tab_Clases;
    private javax.swing.JTree tree_Clases;
    private javax.swing.JTextField txt_ClaseCambiarNombre;
    private javax.swing.JTextField txt_CrearClaseNombre;
    private javax.swing.JTextField txt_CrearMetNombre;
    private javax.swing.JTextField txt_CrearParamNombre;
    private javax.swing.JTextField txt_CrearPropNombre;
    private javax.swing.JTextArea txta_CodigoClases;
    // End of variables declaration//GEN-END:variables

    private final ArrayList<ClaseUML> clases = new ArrayList<ClaseUML>();
    
    // mostrarJDialog(this.diag_CrearMetodo);
    
}
