/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diagramadoruml;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author samuelzun
 */
public class frm_Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_Main.class.getName());

    /**
     * Creates new form GUI
     */
    public frm_Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diag_Clases = new javax.swing.JDialog();
        pnl_Clases = new javax.swing.JPanel();
        lbl_Clases = new javax.swing.JLabel();
        tab_Clases = new javax.swing.JTabbedPane();
        pnl_ClasesDiagrama = new javax.swing.JPanel();
        pnl_ClasesCodigo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_Clases = new javax.swing.JTree();
        btn_ClasesHerencia = new javax.swing.JButton();
        btn_ClasesHerencia1 = new javax.swing.JButton();
        mnb_Clases = new javax.swing.JMenuBar();
        mnb_ClasesArchivo = new javax.swing.JMenu();
        mnb_ClasesAbrir = new javax.swing.JMenuItem();
        mnb_ClasesGuardar = new javax.swing.JMenuItem();
        mnb_ClasesExportar = new javax.swing.JMenu();
        mnb_ClasesExpPDF = new javax.swing.JMenuItem();
        diag_Flujo = new javax.swing.JDialog();
        diag_CrearVariable = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        diag_CrearClase = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_CrearClaseNombre = new javax.swing.JTextField();
        cbox_CrearClasePadre = new javax.swing.JComboBox<>();
        btn_CrearClase = new javax.swing.JToggleButton();
        pop_Clases = new javax.swing.JPopupMenu();
        popmi_ClaseCambiarNombre = new javax.swing.JMenuItem();
        popmi_ClaseCambiarPadre = new javax.swing.JMenuItem();
        popmi_ClaseAgregarPropiedad = new javax.swing.JMenuItem();
        popmi_ClaseAgregarMetodo = new javax.swing.JMenuItem();
        diag_ClaseCambiarNombre = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_ClaseCambiarNombre = new javax.swing.JTextField();
        btn_ClaseCambiarNombre = new javax.swing.JToggleButton();
        pop_Propiedades = new javax.swing.JPopupMenu();
        popmi_PropCambiarNombre = new javax.swing.JMenuItem();
        diag_PropCambiarNombre = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txt_PropCambiarNombre = new javax.swing.JTextField();
        btn_PropNombre = new javax.swing.JToggleButton();
        mnb_Principal = new javax.swing.JMenuBar();
        mn_PrincipalFunciones = new javax.swing.JMenu();
        mni_PrincipalFlujo = new javax.swing.JMenuItem();
        mni_PrincipalClases = new javax.swing.JMenuItem();

        diag_Clases.setPreferredSize(new java.awt.Dimension(1280, 720));
        diag_Clases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diag_ClasesFocusGained(evt);
            }
        });
        diag_Clases.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                diag_ClasesComponentShown(evt);
            }
        });

        lbl_Clases.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_Clases.setText("Clases");

        pnl_ClasesDiagrama.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnl_ClasesDiagramaLayout = new javax.swing.GroupLayout(pnl_ClasesDiagrama);
        pnl_ClasesDiagrama.setLayout(pnl_ClasesDiagramaLayout);
        pnl_ClasesDiagramaLayout.setHorizontalGroup(
            pnl_ClasesDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        pnl_ClasesDiagramaLayout.setVerticalGroup(
            pnl_ClasesDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        tab_Clases.addTab("Diagrama", pnl_ClasesDiagrama);

        javax.swing.GroupLayout pnl_ClasesCodigoLayout = new javax.swing.GroupLayout(pnl_ClasesCodigo);
        pnl_ClasesCodigo.setLayout(pnl_ClasesCodigoLayout);
        pnl_ClasesCodigoLayout.setHorizontalGroup(
            pnl_ClasesCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        pnl_ClasesCodigoLayout.setVerticalGroup(
            pnl_ClasesCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        tab_Clases.addTab("Código", pnl_ClasesCodigo);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_Clases.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_ClasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tree_Clases);

        btn_ClasesHerencia.setText("Herencia");

        btn_ClasesHerencia1.setText("Nueva Clase");
        btn_ClasesHerencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClasesHerencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ClasesLayout = new javax.swing.GroupLayout(pnl_Clases);
        pnl_Clases.setLayout(pnl_ClasesLayout);
        pnl_ClasesLayout.setHorizontalGroup(
            pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesLayout.createSequentialGroup()
                .addGroup(pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_Clases))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btn_ClasesHerencia))
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_ClasesHerencia1)))
                .addGap(97, 97, 97)
                .addComponent(tab_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnl_ClasesLayout.setVerticalGroup(
            pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ClasesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ClasesLayout.createSequentialGroup()
                        .addComponent(lbl_Clases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btn_ClasesHerencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ClasesHerencia1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mnb_ClasesArchivo.setText("Archivo");

        mnb_ClasesAbrir.setText("Abrir");
        mnb_ClasesArchivo.add(mnb_ClasesAbrir);

        mnb_ClasesGuardar.setText("Guardar");
        mnb_ClasesArchivo.add(mnb_ClasesGuardar);

        mnb_Clases.add(mnb_ClasesArchivo);

        mnb_ClasesExportar.setText("Exportar");

        mnb_ClasesExpPDF.setText("Exportar como PDF");
        mnb_ClasesExportar.add(mnb_ClasesExpPDF);

        mnb_Clases.add(mnb_ClasesExportar);

        diag_Clases.setJMenuBar(mnb_Clases);

        javax.swing.GroupLayout diag_ClasesLayout = new javax.swing.GroupLayout(diag_Clases.getContentPane());
        diag_Clases.getContentPane().setLayout(diag_ClasesLayout);
        diag_ClasesLayout.setHorizontalGroup(
            diag_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClasesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        diag_ClasesLayout.setVerticalGroup(
            diag_ClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClasesLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(pnl_Clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diag_FlujoLayout = new javax.swing.GroupLayout(diag_Flujo.getContentPane());
        diag_Flujo.getContentPane().setLayout(diag_FlujoLayout);
        diag_FlujoLayout.setHorizontalGroup(
            diag_FlujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        diag_FlujoLayout.setVerticalGroup(
            diag_FlujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Alcance:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Variable:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "long", "float", "double", "char", "String" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "public", "private", "protected" }));

        jToggleButton1.setText("Crear variable");

        javax.swing.GroupLayout diag_CrearVariableLayout = new javax.swing.GroupLayout(diag_CrearVariable.getContentPane());
        diag_CrearVariable.getContentPane().setLayout(diag_CrearVariableLayout);
        diag_CrearVariableLayout.setHorizontalGroup(
            diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearVariableLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 145, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearVariableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(105, 105, 105))
        );
        diag_CrearVariableLayout.setVerticalGroup(
            diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearVariableLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(diag_CrearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jToggleButton1)
                .addGap(29, 29, 29))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Padre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nombre:");

        cbox_CrearClasePadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearClase.setText("Crear clase");
        btn_CrearClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CrearClaseLayout = new javax.swing.GroupLayout(diag_CrearClase.getContentPane());
        diag_CrearClase.getContentPane().setLayout(diag_CrearClaseLayout);
        diag_CrearClaseLayout.setHorizontalGroup(
            diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearClaseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_CrearClaseNombre)
                    .addComponent(cbox_CrearClasePadre, 0, 145, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearClaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CrearClase)
                .addGap(105, 105, 105))
        );
        diag_CrearClaseLayout.setVerticalGroup(
            diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearClaseLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_CrearClaseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(diag_CrearClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbox_CrearClasePadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btn_CrearClase)
                .addGap(29, 29, 29))
        );

        popmi_ClaseCambiarNombre.setText("Cambiar nombre");
        popmi_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseCambiarNombreActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseCambiarNombre);

        popmi_ClaseCambiarPadre.setText("Cambiar padre");
        pop_Clases.add(popmi_ClaseCambiarPadre);

        popmi_ClaseAgregarPropiedad.setText("jMenuItem1");
        pop_Clases.add(popmi_ClaseAgregarPropiedad);

        popmi_ClaseAgregarMetodo.setText("jMenuItem1");
        popmi_ClaseAgregarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseAgregarMetodoActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseAgregarMetodo);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        btn_ClaseCambiarNombre.setText("Cambiar nombre");
        btn_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClaseCambiarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_ClaseCambiarNombreLayout = new javax.swing.GroupLayout(diag_ClaseCambiarNombre.getContentPane());
        diag_ClaseCambiarNombre.getContentPane().setLayout(diag_ClaseCambiarNombreLayout);
        diag_ClaseCambiarNombreLayout.setHorizontalGroup(
            diag_ClaseCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClaseCambiarNombreLayout.createSequentialGroup()
                .addGroup(diag_ClaseCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_ClaseCambiarNombreLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_ClaseCambiarNombreLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_ClaseCambiarNombre)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_ClaseCambiarNombreLayout.setVerticalGroup(
            diag_ClaseCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ClaseCambiarNombreLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_ClaseCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn_ClaseCambiarNombre)
                .addGap(40, 40, 40))
        );

        popmi_PropCambiarNombre.setText("Cambiar nombre");
        popmi_PropCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_PropCambiarNombreActionPerformed(evt);
            }
        });
        pop_Propiedades.add(popmi_PropCambiarNombre);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nombre:");

        btn_PropNombre.setText("Cambiar nombre");
        btn_PropNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PropNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_PropCambiarNombreLayout = new javax.swing.GroupLayout(diag_PropCambiarNombre.getContentPane());
        diag_PropCambiarNombre.getContentPane().setLayout(diag_PropCambiarNombreLayout);
        diag_PropCambiarNombreLayout.setHorizontalGroup(
            diag_PropCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_PropCambiarNombreLayout.createSequentialGroup()
                .addGroup(diag_PropCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_PropCambiarNombreLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(txt_PropCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_PropCambiarNombreLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_PropNombre)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_PropCambiarNombreLayout.setVerticalGroup(
            diag_PropCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_PropCambiarNombreLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_PropCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_PropCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn_PropNombre)
                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mn_PrincipalFunciones.setText("Funciones");

        mni_PrincipalFlujo.setText("Diagramas de Flujo");
        mni_PrincipalFlujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mni_PrincipalFlujoMouseClicked(evt);
            }
        });
        mni_PrincipalFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PrincipalFlujoActionPerformed(evt);
            }
        });
        mn_PrincipalFunciones.add(mni_PrincipalFlujo);

        mni_PrincipalClases.setText("Diagramas de Clases");
        mni_PrincipalClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PrincipalClasesActionPerformed(evt);
            }
        });
        mn_PrincipalFunciones.add(mni_PrincipalClases);

        mnb_Principal.add(mn_PrincipalFunciones);

        setJMenuBar(mnb_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_PrincipalFlujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mni_PrincipalFlujoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_PrincipalFlujoMouseClicked

    private void mni_PrincipalFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PrincipalFlujoActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_Flujo);
        
    }//GEN-LAST:event_mni_PrincipalFlujoActionPerformed

    private void mni_PrincipalClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PrincipalClasesActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_Clases);
       
    }//GEN-LAST:event_mni_PrincipalClasesActionPerformed

    private void btn_CrearClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearClaseActionPerformed
        // TODO add your handling code here:
        try  {
            if (!this.txt_CrearClaseNombre.getText().trim().isEmpty())  {
                switch (this.cbox_CrearClasePadre.getSelectedIndex()) {
                    case 0 -> {
                        crearClaseUML(
                            this.txt_CrearClaseNombre.getText()
                        );
                    }
                    default -> {
                        crearClaseUML(
                            this.txt_CrearClaseNombre.getText(),
                            (ClaseUML) this.cbox_CrearClasePadre.getSelectedItem()
                        );
                    }
                }
                this.cbox_CrearClasePadre.setModel(
                        crearCBoxModelParaClasesPadre()
                );
                this.tree_Clases.setModel(crearTreeModelClases());
                this.diag_CrearClase.dispose();
                enviarMensaje(this.diag_Clases, "Clase creada.");
            } else  {
                return;
            }
        } catch (Exception e)  {
            imprimirError(e, evt);
            return;
        }
    }//GEN-LAST:event_btn_CrearClaseActionPerformed

    private void diag_ClasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diag_ClasesFocusGained
        // TODO add your handling code here:
        this.tree_Clases.setModel(
                crearTreeModelClases()
        );
        
    }//GEN-LAST:event_diag_ClasesFocusGained

    private void btn_ClasesHerencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClasesHerencia1ActionPerformed
        // TODO add your handling code here:
        mostrarJDialog(this.diag_CrearClase);
        
    }//GEN-LAST:event_btn_ClasesHerencia1ActionPerformed

    private void diag_ClasesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_diag_ClasesComponentShown
        // TODO add your handling code here:
        this.tree_Clases.setModel(
                crearTreeModelClases()
        );
        
    }//GEN-LAST:event_diag_ClasesComponentShown

    private void popmi_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:
        
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML) {
            mostrarJDialog(this.diag_ClaseCambiarNombre);
        }
        
    }//GEN-LAST:event_popmi_ClaseCambiarNombreActionPerformed

    private void tree_ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_ClasesMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            
            Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
            if (objetoSeleccionado instanceof ClaseUML) {
                this.pop_Clases.show(this.tree_Clases, evt.getX(), evt.getY());
            } else if (objetoSeleccionado instanceof Propiedad) {
                this.pop_Propiedades.show(this.tree_Clases, evt.getX(), evt.getY());
            }
            
        }
        
    }//GEN-LAST:event_tree_ClasesMouseClicked

    private void btn_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML) {
            
            ClaseUML clase = (ClaseUML) ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                clase.setNombre(this.txt_ClaseCambiarNombre.getText());
                this.diag_ClaseCambiarNombre.dispose();
                enviarMensaje(this.diag_ClaseCambiarNombre, "Nombre cambiado.");
            }
            
        }
    }//GEN-LAST:event_btn_ClaseCambiarNombreActionPerformed

    private void popmi_PropCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_PropCambiarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popmi_PropCambiarNombreActionPerformed

    private void popmi_ClaseAgregarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseAgregarMetodoActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clases.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof ClaseUML) {
            
            ClaseUML clase = (ClaseUML) objetoSeleccionado;
            if (!this.txt_PropCambiarNombre.getText().trim().isEmpty())  {
                clase.setNombre(this.txt_PropCambiarNombre.getText());
                this.diag_PropCambiarNombre.dispose();
                enviarMensaje(this.diag_PropCambiarNombre, "Nombre cambiado.");
            }
            
        }
        
    }//GEN-LAST:event_popmi_ClaseAgregarMetodoActionPerformed

    private void btn_PropNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PropNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PropNombreActionPerformed
    
    private DefaultTreeModel crearTreeModelClases() {
        
        DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode("Clases");
        for (ClaseUML clase: clases) {
            DefaultMutableTreeNode nodoClase = new DefaultMutableTreeNode(clase);
            DefaultMutableTreeNode nodoPropiedades = new DefaultMutableTreeNode("Propiedades");
            DefaultMutableTreeNode nodoMetodos = new DefaultMutableTreeNode("Métodos");
            for (Propiedad prop: clase.getPropiedades()) {
                nodoPropiedades.add(new DefaultMutableTreeNode(prop));
            }
            for (Metodo met: clase.getMetodos()) {
                nodoMetodos.add(new DefaultMutableTreeNode(met));
            }
            nodoClase.add(nodoPropiedades); nodoClase.add(nodoMetodos);
            nodoRaiz.add(nodoClase);
        }
        
        return new DefaultTreeModel(nodoRaiz);
        
    }
    
    private DefaultComboBoxModel crearCBoxModelParaClasesPadre() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Sin clase");
        for (ClaseUML clase: this.clases) {
            modelo.addElement(clase);
        }
        return modelo;
    }
    
    private void mostrarJDialog(javax.swing.JDialog diag) {
        diag.pack();
        diag.setVisible(true);
    }
    
    private void enviarMensaje(java.awt.Component comp, String msg) {
        JOptionPane.showMessageDialog(comp, msg, "", -1);
    }
    
    private void crearClaseUML(String nombre) {
        clases.add(new ClaseUML(
                nombre
        ));
    }
    private void crearClaseUML(String nombre, ClaseUML padre) {
        clases.add(new ClaseUML(
                nombre,
                padre
        ));
    }
    
    private void imprimirError(Exception e, java.awt.event.ActionEvent evt) {
        System.out.println(e.getCause()+" en "+evt.getActionCommand());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Main().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ClaseCambiarNombre;
    private javax.swing.JButton btn_ClasesHerencia;
    private javax.swing.JButton btn_ClasesHerencia1;
    private javax.swing.JToggleButton btn_CrearClase;
    private javax.swing.JToggleButton btn_PropNombre;
    private javax.swing.JComboBox<String> cbox_CrearClasePadre;
    private javax.swing.JDialog diag_ClaseCambiarNombre;
    private javax.swing.JDialog diag_Clases;
    private javax.swing.JDialog diag_CrearClase;
    private javax.swing.JDialog diag_CrearVariable;
    private javax.swing.JDialog diag_Flujo;
    private javax.swing.JDialog diag_PropCambiarNombre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_Clases;
    private javax.swing.JMenu mn_PrincipalFunciones;
    private javax.swing.JMenuBar mnb_Clases;
    private javax.swing.JMenuItem mnb_ClasesAbrir;
    private javax.swing.JMenu mnb_ClasesArchivo;
    private javax.swing.JMenuItem mnb_ClasesExpPDF;
    private javax.swing.JMenu mnb_ClasesExportar;
    private javax.swing.JMenuItem mnb_ClasesGuardar;
    private javax.swing.JMenuBar mnb_Principal;
    private javax.swing.JMenuItem mni_PrincipalClases;
    private javax.swing.JMenuItem mni_PrincipalFlujo;
    private javax.swing.JPanel pnl_Clases;
    private javax.swing.JPanel pnl_ClasesCodigo;
    private javax.swing.JPanel pnl_ClasesDiagrama;
    private javax.swing.JPopupMenu pop_Clases;
    private javax.swing.JPopupMenu pop_Propiedades;
    private javax.swing.JMenuItem popmi_ClaseAgregarMetodo;
    private javax.swing.JMenuItem popmi_ClaseAgregarPropiedad;
    private javax.swing.JMenuItem popmi_ClaseCambiarNombre;
    private javax.swing.JMenuItem popmi_ClaseCambiarPadre;
    private javax.swing.JMenuItem popmi_PropCambiarNombre;
    private javax.swing.JTabbedPane tab_Clases;
    private javax.swing.JTree tree_Clases;
    private javax.swing.JTextField txt_ClaseCambiarNombre;
    private javax.swing.JTextField txt_CrearClaseNombre;
    private javax.swing.JTextField txt_PropCambiarNombre;
    // End of variables declaration//GEN-END:variables

    private final ArrayList<ClaseUML> clases = new ArrayList<ClaseUML>();
    
}
