/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package diagramadoruml;

import java.awt.Graphics;
import java.awt.Point;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author samuelzun
 */
public class pnl_ClaseUML extends JPanel {

    /**
     * Creates new form TreeDeClase
     * @param clase
     * @param frm
     */
    public pnl_ClaseUML(ClaseUML clase, frm_Main frm) {
        
        this.clase = clase;
        this.frm = frm;
        
        
        initComponents();
        
        
        DefaultComboBoxModel paramModeloTipo = (DefaultComboBoxModel) this.cbox_CrearParamTipo.getModel();
        paramModeloTipo.removeAllElements();
        for (int i = 1; i < Tipo.values().length; i++) {
            paramModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel propModeloTipo = (DefaultComboBoxModel) this.cbox_CrearPropTipo.getModel();
        propModeloTipo.removeAllElements();
        for (int i = 1; i < Tipo.values().length; i++) {
            propModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel propModeloAcceso = (DefaultComboBoxModel) this.cbox_CrearPropAcceso.getModel();
        propModeloAcceso.removeAllElements();
        for (Acceso acceso: Acceso.values()) {
            propModeloAcceso.addElement(
                    acceso
            );
        }
        
        DefaultComboBoxModel metModeloTipo = (DefaultComboBoxModel) this.cbox_CrearMetTipo.getModel();
        metModeloTipo.removeAllElements();
        for (int i = 0; i < Tipo.values().length; i++) {
            metModeloTipo.addElement(
                    Tipo.values()[i]
            );
        }
        
        DefaultComboBoxModel metModeloAcceso = (DefaultComboBoxModel) this.cbox_CrearMetAcceso.getModel();
        metModeloAcceso.removeAllElements();
        for (Acceso acceso: Acceso.values()) {
            metModeloAcceso.addElement(
                    acceso
            );
        }

        this.tree_Clase.setModel(
                new DefaultTreeModel(clase.formaNodo())
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_Clases = new javax.swing.JPopupMenu();
        popmi_ClaseCambiarNombre = new javax.swing.JMenuItem();
        popmi_ClaseAgregarPropiedad = new javax.swing.JMenuItem();
        popmi_ClaseAgregarMetodo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        popmi_ClaseEliminar = new javax.swing.JMenuItem();
        diag_CrearMetodo = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_CrearMetNombre = new javax.swing.JTextField();
        cbox_CrearMetTipo = new javax.swing.JComboBox<>();
        btn_CrearMet = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        cbox_CrearMetAcceso = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_CrearMetParametros = new javax.swing.JList<>();
        btn_CrearMetAgregarParametro = new javax.swing.JToggleButton();
        diag_CrearProp = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_CrearPropNombre = new javax.swing.JTextField();
        cbox_CrearPropTipo = new javax.swing.JComboBox<>();
        btn_CrearProp = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        cbox_CrearPropAcceso = new javax.swing.JComboBox<>();
        diag_CambiarNombre = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_ClaseCambiarNombre = new javax.swing.JTextField();
        btn_ClaseCambiarNombre = new javax.swing.JToggleButton();
        diag_CrearParametro = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        txt_CrearParamNombre = new javax.swing.JTextField();
        btn_CrearParam = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        cbox_CrearParamTipo = new javax.swing.JComboBox<>();
        pop_PropMtd = new javax.swing.JPopupMenu();
        popmi_PropMtdCambiarNombre = new javax.swing.JMenuItem();
        popmi_PropMtdEliminar = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree_Clase = new javax.swing.JTree();

        popmi_ClaseCambiarNombre.setText("Cambiar nombre");
        popmi_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseCambiarNombreActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseCambiarNombre);

        popmi_ClaseAgregarPropiedad.setText("Agregar propiedad");
        popmi_ClaseAgregarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseAgregarPropiedadActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseAgregarPropiedad);

        popmi_ClaseAgregarMetodo.setText("Crear método");
        popmi_ClaseAgregarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseAgregarMetodoActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseAgregarMetodo);
        pop_Clases.add(jSeparator1);

        popmi_ClaseEliminar.setText("Eliminar esta clase");
        popmi_ClaseEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_ClaseEliminarActionPerformed(evt);
            }
        });
        pop_Clases.add(popmi_ClaseEliminar);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Retorno:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nombre:");

        cbox_CrearMetTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearMet.setText("Crear método");
        btn_CrearMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearMetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Acceso:");

        cbox_CrearMetAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        list_CrearMetParametros.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(list_CrearMetParametros);

        btn_CrearMetAgregarParametro.setText("Agregar\nparámetro");
        btn_CrearMetAgregarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearMetAgregarParametroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CrearMetodoLayout = new javax.swing.GroupLayout(diag_CrearMetodo.getContentPane());
        diag_CrearMetodo.getContentPane().setLayout(diag_CrearMetodoLayout);
        diag_CrearMetodoLayout.setHorizontalGroup(
            diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(btn_CrearMetAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbox_CrearMetAcceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_CrearMetNombre)
                                .addComponent(cbox_CrearMetTipo, 0, 145, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_CrearMet)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        diag_CrearMetodoLayout.setVerticalGroup(
            diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_CrearMetNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbox_CrearMetTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbox_CrearMetAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(diag_CrearMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearMetodoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_CrearMetodoLayout.createSequentialGroup()
                        .addComponent(btn_CrearMetAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(btn_CrearMet)
                .addGap(39, 39, 39))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tipo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        cbox_CrearPropTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        btn_CrearProp.setText("Crear propiedad");
        btn_CrearProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearPropActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Acceso:");

        cbox_CrearPropAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin padre" }));

        javax.swing.GroupLayout diag_CrearPropLayout = new javax.swing.GroupLayout(diag_CrearProp.getContentPane());
        diag_CrearProp.getContentPane().setLayout(diag_CrearPropLayout);
        diag_CrearPropLayout.setHorizontalGroup(
            diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearPropLayout.createSequentialGroup()
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearPropLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35)
                        .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbox_CrearPropAcceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_CrearPropNombre)
                            .addComponent(cbox_CrearPropTipo, 0, 145, Short.MAX_VALUE)))
                    .addGroup(diag_CrearPropLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_CrearProp)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CrearPropLayout.setVerticalGroup(
            diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearPropLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_CrearPropNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbox_CrearPropTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(diag_CrearPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbox_CrearPropAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btn_CrearProp)
                .addGap(31, 31, 31))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        btn_ClaseCambiarNombre.setText("Cambiar nombre");
        btn_ClaseCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClaseCambiarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_CambiarNombreLayout = new javax.swing.GroupLayout(diag_CambiarNombre.getContentPane());
        diag_CambiarNombre.getContentPane().setLayout(diag_CambiarNombreLayout);
        diag_CambiarNombreLayout.setHorizontalGroup(
            diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                .addGroup(diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_ClaseCambiarNombre)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CambiarNombreLayout.setVerticalGroup(
            diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CambiarNombreLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_ClaseCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn_ClaseCambiarNombre)
                .addGap(40, 40, 40))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nombre:");

        btn_CrearParam.setText("Crear parametro");
        btn_CrearParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearParamActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Tipo:");

        cbox_CrearParamTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout diag_CrearParametroLayout = new javax.swing.GroupLayout(diag_CrearParametro.getContentPane());
        diag_CrearParametro.getContentPane().setLayout(diag_CrearParametroLayout);
        diag_CrearParametroLayout.setHorizontalGroup(
            diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_CrearParam))
                    .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CrearParamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_CrearParamTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diag_CrearParametroLayout.setVerticalGroup(
            diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_CrearParametroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txt_CrearParamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(diag_CrearParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbox_CrearParamTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_CrearParam)
                .addGap(40, 40, 40))
        );

        popmi_PropMtdCambiarNombre.setText("Cambiar nombre");
        popmi_PropMtdCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_PropMtdCambiarNombreActionPerformed(evt);
            }
        });
        pop_PropMtd.add(popmi_PropMtdCambiarNombre);

        popmi_PropMtdEliminar.setText("Borrar elemento");
        popmi_PropMtdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmi_PropMtdEliminarActionPerformed(evt);
            }
        });
        pop_PropMtd.add(popmi_PropMtdEliminar);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        tree_Clase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tree_ClaseMouseDragged(evt);
            }
        });
        tree_Clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tree_ClaseMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tree_Clase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void tree_ClaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_ClaseMousePressed
        // TODO add your handling code here:
        esquinaAnterior = evt.getPoint();
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            if (this.tree_Clase.getSelectionPath() == null) {
                return;
            }
            
            Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject();
            if (objetoSeleccionado instanceof ClaseUML) {
                this.pop_Clases.show(this.tree_Clase, evt.getX(), evt.getY());
            } else if (objetoSeleccionado instanceof Propiedad) {
                this.pop_PropMtd.show(this.tree_Clase, evt.getX(), evt.getY());
            }
            
        }
        esquinaAnterior = evt.getPoint();
        
    }//GEN-LAST:event_tree_ClaseMousePressed

    private void tree_ClaseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_ClaseMouseDragged
        // TODO add your handling code here:
        Thread hilo = new Thread(
                () -> {
                    try {
                        Point esquinaAhora = evt.getPoint();

                        Thread.sleep(50);

                        int x = (int)(evt.getXOnScreen() - getLocationOnScreen().x + getX() - esquinaAnterior.getX() - (getWidth()/2));
                        int y = (int)(evt.getYOnScreen() - getLocationOnScreen().y + getY() - esquinaAnterior.getY() - (getHeight()/2));

                        esquina.translate(
                                x
                                ,
                                y
                        );

                        esquinaAnterior = esquina;
                        SwingUtilities.invokeLater(
                                () -> {
                                    repaint();
                                }
                        );
                    } catch (InterruptedException ex) {
                        esquina = new Point(0, 0);
                        esquinaAnterior = new Point(0, 0);
                    }
                }
        );
        hilo.start();
        
        
        
    }//GEN-LAST:event_tree_ClaseMouseDragged

    private void popmi_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:

        if (((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {

            this.txt_ClaseCambiarNombre.setText(clase.getNombre());

        }
        frm.mostrarJDialog(this.diag_CambiarNombre);

    }//GEN-LAST:event_popmi_ClaseCambiarNombreActionPerformed

    private void popmi_ClaseAgregarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseAgregarPropiedadActionPerformed
        // TODO add your handling code here:
        frm.mostrarJDialog(this.diag_CrearProp);

    }//GEN-LAST:event_popmi_ClaseAgregarPropiedadActionPerformed

    private void popmi_ClaseAgregarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseAgregarMetodoActionPerformed
        // TODO add your handling code here:
        frm.mostrarJDialog(this.diag_CrearMetodo);

    }//GEN-LAST:event_popmi_ClaseAgregarMetodoActionPerformed

    private void popmi_ClaseEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_ClaseEliminarActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof ClaseUML clase) {

            Data.getClases().remove(clase);
            frm.refrescarModelosClase();
            frm.enviarMensaje(frm, "Clase removida");

        }

    }//GEN-LAST:event_popmi_ClaseEliminarActionPerformed

    private void btn_CrearMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearMetActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {

            try {
                if (!this.txt_CrearMetNombre.getText().trim().isEmpty()) {

                    Metodo nuevoMetodo = new Metodo(
                        this.txt_CrearMetNombre.getText(),
                        (Tipo) this.cbox_CrearMetTipo.getSelectedItem(),
                        (Acceso) this.cbox_CrearMetAcceso.getSelectedItem()
                    );

                    if (this.list_CrearMetParametros.getModel().getSize() != 0) {
                        for (int i = 0; i < this.list_CrearMetParametros.getModel().getSize(); i++) {
                            nuevoMetodo.getParametros().add(
                                (Propiedad) ( (DefaultListModel) this.list_CrearMetParametros.getModel() ).get(i)
                            );
                        }
                        ( (DefaultListModel) this.list_CrearMetParametros.getModel() ).removeAllElements();
                    }

                    clase.getMetodos().add(
                        nuevoMetodo
                    );

                    frm.refrescarModelosClase();
                    this.diag_CrearMetodo.dispose();
                    frm.limpiar(this.txt_CrearMetNombre);
                    frm.enviarMensaje(frm, "Método creado.");

                }
            } catch (Exception e) {
            }

        } else {
            System.out.println("hola");
        }

    }//GEN-LAST:event_btn_CrearMetActionPerformed

    private void btn_CrearMetAgregarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearMetAgregarParametroActionPerformed
        // TODO add your handling code here:
        frm.mostrarJDialog(this.diag_CrearParametro);

    }//GEN-LAST:event_btn_CrearMetAgregarParametroActionPerformed

    private void btn_CrearPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearPropActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject() instanceof ClaseUML clase) {

            try {
                if (!this.txt_CrearPropNombre.getText().trim().isEmpty()) {

                    clase.getPropiedades().add(
                        new Propiedad(
                            this.txt_CrearPropNombre.getText(),
                            (Tipo) this.cbox_CrearPropTipo.getSelectedItem(),
                            (Acceso) this.cbox_CrearPropAcceso.getSelectedItem()
                        )
                    );
                    this.diag_CrearProp.dispose();
                    frm.refrescarModelosClase();
                    frm.enviarMensaje(frm, "Clase creada.");

                }
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_btn_CrearPropActionPerformed

    private void btn_ClaseCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClaseCambiarNombreActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof ClaseUML clase) {

            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                clase.setNombre(this.txt_ClaseCambiarNombre.getText());
                this.diag_CambiarNombre.dispose();
                frm.refrescarModelosClase();
                frm.enviarMensaje(frm, "Nombre cambiado.");
            }

        } else if (objetoSeleccionado instanceof Propiedad prop) {

            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                boolean tieneHijos = false;
                for (ClaseUML clase: Data.todasLasClases()) {
                    if (clase.getPropiedades().contains(prop)) {
                        tieneHijos = !clase.getHijos().isEmpty();
                    }
                }
                if (tieneHijos && prop.getAcceso() == Acceso.PROTECTED) {
                    if (JOptionPane.showConfirmDialog(this, "Realizar este cambio eliminara todos los hijos de la clase, desea continuar?", "", -1) == JOptionPane.CANCEL_OPTION) {
                        this.diag_CambiarNombre.dispose();
                        return;
                    }
                }
                prop.setNombre(this.txt_ClaseCambiarNombre.getText());
                if (tieneHijos && prop.getAcceso() == Acceso.PROTECTED) {
                    for (ClaseUML clase: Data.todasLasClases()) {
                        if (clase.getPropiedades().contains(prop)) {
                            for (ClaseUML claseHija: Data.todasLasClases(clase.getHijos())) {
                                frm.eliminarPanelEnDiagramador(claseHija);
                            }
                            clase.getHijos().clear();
                            break;
                        }
                    }
                }
                this.diag_CambiarNombre.dispose();
                frm.refrescarModelosClase();
                frm.enviarMensaje(frm, "Nombre cambiado.");
            }

        } else if (objetoSeleccionado instanceof Metodo mtd) {
            
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                boolean tieneHijos = false;
                for (ClaseUML clase: Data.todasLasClases()) {
                    if (clase.getMetodos().contains(mtd)) {
                        tieneHijos = !clase.getHijos().isEmpty();
                    }
                }
                if (tieneHijos && mtd.getAcceso() == Acceso.PROTECTED) {
                    if (JOptionPane.showConfirmDialog(this, "Realizar este cambio eliminara todos los hijos de la clase, desea continuar?", "", -1) == JOptionPane.CANCEL_OPTION) {
                        this.diag_CambiarNombre.dispose();
                        return;
                    }
                }
                mtd.setNombre(this.txt_ClaseCambiarNombre.getText());
                if (tieneHijos && mtd.getAcceso() == Acceso.PROTECTED) {
                    for (ClaseUML clase: Data.todasLasClases()) {
                        if (clase.getMetodos().contains(mtd)) {
                            for (ClaseUML claseHija: Data.todasLasClases(clase.getHijos())) {
                                frm.eliminarPanelEnDiagramador(claseHija);
                            }
                            clase.getHijos().clear();
                            break;
                        }
                    }
                }
                this.diag_CambiarNombre.dispose();
                frm.refrescarModelosClase();
                frm.enviarMensaje(frm, "Nombre cambiado.");
            }
            
        }
    }//GEN-LAST:event_btn_ClaseCambiarNombreActionPerformed

    private void btn_CrearParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearParamActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = (DefaultListModel) this.list_CrearMetParametros.getModel();
        Propiedad param = new Propiedad(
            this.txt_CrearParamNombre.getText(),
            (Tipo) this.cbox_CrearParamTipo.getSelectedItem()
        );
        modeloLista.addElement(param);
        this.diag_CrearParametro.dispose();

    }//GEN-LAST:event_btn_CrearParamActionPerformed

    private void popmi_PropMtdCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_PropMtdCambiarNombreActionPerformed
        // TODO add your handling code here:
        if (((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject() instanceof Propiedad prop) {

            this.txt_ClaseCambiarNombre.setText(prop.getNombre());

        }
        frm.mostrarJDialog(this.diag_CambiarNombre);

    }//GEN-LAST:event_popmi_PropMtdCambiarNombreActionPerformed

    private void popmi_PropMtdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmi_PropMtdEliminarActionPerformed
        // TODO add your handling code here:
        Object objetoSeleccionado = ((DefaultMutableTreeNode)this.tree_Clase.getSelectionPath().getLastPathComponent()).getUserObject();
        if (objetoSeleccionado instanceof Propiedad prop) {
            
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                boolean tieneHijos = false;
                for (ClaseUML clase: Data.todasLasClases()) {
                    if (clase.getPropiedades().contains(prop)) {
                        tieneHijos = !clase.getHijos().isEmpty();
                    }
                }
                if (tieneHijos && prop.getAcceso() == Acceso.PROTECTED) {
                    if (JOptionPane.showConfirmDialog(this, "Borrar este elemento eliminara todos los hijos de la clase, desea continuar?", "", -1) == JOptionPane.CANCEL_OPTION) {
                        return;
                    }
                }
                if (tieneHijos && prop.getAcceso() == Acceso.PROTECTED) {
                    for (ClaseUML clase: Data.todasLasClases()) {
                        if (clase.getPropiedades().contains(prop)) {
                            for (ClaseUML claseHija: Data.todasLasClases(clase.getHijos())) {
                                frm.eliminarPanelEnDiagramador(claseHija);
                            }
                            clase.getHijos().clear();
                            break;
                        }
                    }
                }
                for (ClaseUML clase: Data.todasLasClases()) {
                    clase.getPropiedades().remove(prop);
                }
                frm.refrescarModelosClase();
                frm.enviarMensaje(frm, "Elemento borrado.");
            }
            
        } else if (objetoSeleccionado instanceof Metodo mtd) {
            
            if (!this.txt_ClaseCambiarNombre.getText().trim().isEmpty())  {
                boolean tieneHijos = false;
                for (ClaseUML clase: Data.todasLasClases()) {
                    if (clase.getMetodos().contains(mtd)) {
                        tieneHijos = !clase.getHijos().isEmpty();
                    }
                }
                if (tieneHijos && mtd.getAcceso() == Acceso.PROTECTED) {
                    if (JOptionPane.showConfirmDialog(this, "Borrar este elemento eliminara todos los hijos de la clase, desea continuar?", "", -1) == JOptionPane.CANCEL_OPTION) {
                        return;
                    }
                }
                if (tieneHijos && mtd.getAcceso() == Acceso.PROTECTED) {
                    for (ClaseUML clase: Data.todasLasClases()) {
                        if (clase.getMetodos().contains(mtd)) {
                            for (ClaseUML claseHija: Data.todasLasClases(clase.getHijos())) {
                                frm.eliminarPanelEnDiagramador(claseHija);
                            }
                            clase.getHijos().clear();
                            break;
                        }
                    }
                }
                for (ClaseUML clase: Data.todasLasClases()) {
                    clase.getMetodos().remove(mtd);
                }
                frm.refrescarModelosClase();
                frm.enviarMensaje(frm, "Elemento borrado.");
            }
            
        }
        
    }//GEN-LAST:event_popmi_PropMtdEliminarActionPerformed

    public void refrescarModeloClase() {
        this.tree_Clase.setModel(
                new DefaultTreeModel(clase.formaNodo())
        );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ClaseCambiarNombre;
    private javax.swing.JToggleButton btn_CrearMet;
    private javax.swing.JToggleButton btn_CrearMetAgregarParametro;
    private javax.swing.JToggleButton btn_CrearParam;
    private javax.swing.JToggleButton btn_CrearProp;
    private javax.swing.JComboBox<String> cbox_CrearMetAcceso;
    private javax.swing.JComboBox<String> cbox_CrearMetTipo;
    private javax.swing.JComboBox<String> cbox_CrearParamTipo;
    private javax.swing.JComboBox<String> cbox_CrearPropAcceso;
    private javax.swing.JComboBox<String> cbox_CrearPropTipo;
    private javax.swing.JDialog diag_CambiarNombre;
    private javax.swing.JDialog diag_CrearMetodo;
    private javax.swing.JDialog diag_CrearParametro;
    private javax.swing.JDialog diag_CrearProp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JList<String> list_CrearMetParametros;
    private javax.swing.JPopupMenu pop_Clases;
    private javax.swing.JPopupMenu pop_PropMtd;
    private javax.swing.JMenuItem popmi_ClaseAgregarMetodo;
    private javax.swing.JMenuItem popmi_ClaseAgregarPropiedad;
    private javax.swing.JMenuItem popmi_ClaseCambiarNombre;
    private javax.swing.JMenuItem popmi_ClaseEliminar;
    private javax.swing.JMenuItem popmi_PropMtdCambiarNombre;
    private javax.swing.JMenuItem popmi_PropMtdEliminar;
    private javax.swing.JTree tree_Clase;
    private javax.swing.JTextField txt_ClaseCambiarNombre;
    private javax.swing.JTextField txt_CrearMetNombre;
    private javax.swing.JTextField txt_CrearParamNombre;
    private javax.swing.JTextField txt_CrearPropNombre;
    // End of variables declaration//GEN-END:variables
    
    private final frm_Main frm;
    private final ClaseUML clase;
    
    Point esquina = new Point(0, 0);
    Point esquinaAnterior;
    
    public void paintComponent(Graphics g) {
        this.setLocation(esquina);
        super.paintComponent(g);
    }

    public ClaseUML getClase() {
        return clase;
    }

    public void setEsquina(Point esquina) {
        this.esquina = esquina;
    }
}
