/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package diagramadoruml;

/**
 *
 * @author Ryzen Gaming
 */
public class pnl_FlujoUML extends javax.swing.JPanel {

    /**
     * Creates new form pnl_OperacionUML
     */
    public pnl_FlujoUML(FlujoUML flujo) {
        
        this.flujo = flujo;
        initComponents();
        this.cambiarLblNombre(flujo.getNombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TipoOperacion = new javax.swing.JLabel();
        lbl_NombreOperacion = new javax.swing.JLabel();

        lbl_TipoOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TipoOperacion.setText(" *opr*");

        lbl_NombreOperacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NombreOperacion.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NombreOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(lbl_TipoOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_NombreOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lbl_TipoOperacion))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_NombreOperacion;
    private javax.swing.JLabel lbl_TipoOperacion;
    // End of variables declaration//GEN-END:variables
    
    private FlujoUML flujo;
    
    public void cambiarLblTipo(String str) {
        this.lbl_TipoOperacion.setText(str);
    }
    
    public void cambiarLblNombre(String str) {
        this.lbl_NombreOperacion.setText(str);
    }
    
}
